Add a catch all

diff --git a/df b/df
--- a/df
+++ b/df
@@ -21,6 +21,11 @@ while getopts ':fdh' opts; do
     --)
       break
       ;;
+    *)
+      echo "Invalid option provided"
+      echo "Exiting"
+      exit 1
+      ;;
   esac
 done
 shift $((OPTIND-1))
