refactor and categorise

diff --git a/dots b/dots
--- a/dots
+++ b/dots
@@ -14,13 +14,7 @@
 
 IFS=":"
 
-v_echo() {
-  [ "$get_wordy" = true ] && echo "$@"
-}
-
-err() {
-  printf '\033[31merror:\033[0m %s\n' "$@" >&2
-}
+####### Meta Functions #########
 
 help() {
   case $1 in
@@ -97,6 +91,34 @@ Options:
       ;;
   esac
 }
+
+force() {
+  echo "Force will disable all saftey checks."
+  echo "It is not recommended unless completely necessary."
+  echo "Are you sure? [yN]"
+  read -r yn
+  case $yn in
+    [Yy] | [Yy][Ee][Ss] )
+      force=true
+      ;;
+    "" | [Nn] | [Nn][Oo] )
+      echo "Good choice :)"
+      exit
+      ;;
+    *)
+      err "Option not recognised"
+      exit
+  esac
+  [ "$@" ] && run_cmd "$@"
+}
+
+# Called by `dots verbose cmd` - equivelent to -v flag
+verbose() {
+  get_wordy=true
+  run_cmd "$@"
+}
+
+####### Subcommand Functions #########
 
 store() {
   while getopts ':hDvf' opts; do
@@ -383,6 +405,38 @@ unlink() {
   done
 }
 
+####### Git Wrapper Functions #########
+
+pull() {
+  git -C "$repo_location" fetch "$@"
+  tmp=$(mktemp)
+  git -C "$repo_location" diff --name-only --diff-filter=D HEAD FETCH_HEAD > "$tmp"
+  while IFS= read -r f; do # 'IFS= ' don't split, 'read -r f' read each line without escaping as $f
+    symlink="$HOME/$f"
+    if [ -L "$symlink" ]; then
+      if [ "$dryrun" = true ]; then
+        v_echo "Dry run: would remove dead symlink $symlink"
+      else
+        rm "$symlink"
+        v_echo "Removed dead symlink $symlink"
+      fi
+    fi
+  done < "$tmp"
+  rm "$tmp"
+
+  [ ! "$dryrun" = true ] && git -C "$repo_location" pull "$@"
+}
+
+####### Helper Functions #########
+
+v_echo() {
+  [ "$get_wordy" = true ] && echo "$@"
+}
+
+err() {
+  printf '\033[31merror:\033[0m %s\n' "$@" >&2
+}
+
 is_ignored() {
   found=false
   for i in $ignoreList; do
@@ -427,61 +481,6 @@ path_from_home() {
   esac
 }
 
-pull() {
-  git -C "$repo_location" fetch "$@"
-  tmp=$(mktemp)
-  git -C "$repo_location" diff --name-only --diff-filter=D HEAD FETCH_HEAD > "$tmp"
-  while IFS= read -r f; do # 'IFS= ' don't split, 'read -r f' read each line without escaping as $f
-    symlink="$HOME/$f"
-    if [ -L "$symlink" ]; then
-      if [ "$dryrun" = true ]; then
-        v_echo "Dry run: would remove dead symlink $symlink"
-      else
-        rm "$symlink"
-        v_echo "Removed dead symlink $symlink"
-      fi
-    fi
-  done < "$tmp"
-  rm "$tmp"
-
-  [ ! "$dryrun" = true ] && git -C "$repo_location" pull "$@"
-}
-
-# Get the path to the dotfile repo
-repo_location=$(dirname "$(realpath "$0")")
-script_name=$(basename "$0")
-
-# Build the ignore list
-ignoreList=".git:.gitignore:.dotignore:.dotsignore:README.md:LICENSE"
-[ -f "$repo_location/.dotignore" ] && ignoreList="$ignoreList:$(tr '\n' ':' < "$repo_location/.dotignore")"
-[ -f "$repo_location/.dotsignore" ] && ignoreList="$ignoreList:$(tr '\n' ':' < "$repo_location/.dotsignore")"
-
-force() {
-  echo "Force will disable all saftey checks."
-  echo "It is not recommended unless completely necessary."
-  echo "Are you sure? [yN]"
-  read -r yn
-  case $yn in
-    [Yy] | [Yy][Ee][Ss] )
-      force=true
-      ;;
-    "" | [Nn] | [Nn][Oo] )
-      echo "Good choice :)"
-      exit
-      ;;
-    *)
-      err "Option not recognised"
-      exit
-  esac
-  [ "$@" ] && run_cmd "$@"
-}
-
-# Called by `dots verbose cmd` - equivelent to -v flag
-verbose() {
-  get_wordy=true
-  run_cmd "$@"
-}
-
 run_cmd() {
   cmd="$1"
   if command -V "$cmd" 2> /dev/null | grep -qwi function; then
@@ -493,6 +492,17 @@ run_cmd() {
     help
   fi
 }
+
+####### END OF FUNCTIONS #########
+
+# Get the path to the dotfile repo
+repo_location=$(dirname "$(realpath "$0")")
+script_name=$(basename "$0")
+
+# Build the ignore list
+ignoreList=".git:.gitignore:.dotignore:.dotsignore:README.md:LICENSE"
+[ -f "$repo_location/.dotignore" ] && ignoreList="$ignoreList:$(tr '\n' ':' < "$repo_location/.dotignore")"
+[ -f "$repo_location/.dotsignore" ] && ignoreList="$ignoreList:$(tr '\n' ':' < "$repo_location/.dotsignore")"
 
 while getopts ':dDfvh' opts; do
   case $opts in
